/**
 * Refresh tokens: generation, and the one-way material stored in their place.
 *
 * **Why a plain hash and not a password KDF.** `IDENTITY_AUTH_ARCHITECTURE`
 * §23 writes the stored column as `argon2id(refresh_token)`, and the intent
 * behind that — never store the token itself — is what this module
 * implements. The primitive differs, for the same reason K1 §7.1 gives for
 * removing PBKDF2: a slow hash exists to make *guessing* expensive, and there
 * is nothing here to guess. A refresh token is 256 bits of CSPRNG output
 * generated by this server, not a human secret drawn from a small space.
 * Argon2id against it would reduce an attacker's work from 2^256 to 2^256 and
 * add latency to every refresh.
 *
 * What the digest actually defends is a **stolen database**: an attacker with
 * the rows must not be able to present a token. SHA-256 with domain
 * separation achieves that against a uniform 256-bit input, and is what
 * opaque session tokens are normally stored as.
 *
 * This is a deliberate, recorded divergence in *primitive*, not in property,
 * and it is reported rather than written into the architecture document. The
 * `TokenDigest` port exists so that swapping in Argon2id — if the OTP phase
 * introduces that dependency, where it **is** the right primitive because a
 * six-digit code has a tiny guess space — is one adapter and no call-site
 * change.
 */

/** Bytes of entropy in a refresh token. 256 bits, uniform. */
const REFRESH_TOKEN_BYTES = 32;

/** Domain separator, so a digest computed here is meaningless elsewhere. */
const DIGEST_DOMAIN = 'aba/auth/refresh/v1';

export interface TokenDigest {
  /** One-way material stored in place of the token. */
  compute(token: string): Promise<string>;
}

function toHex(bytes: Uint8Array): string {
  return [...bytes].map((byte) => byte.toString(16).padStart(2, '0')).join('');
}

/** A new refresh token. Returned to the caller once and never stored. */
export function newRefreshToken(): string {
  const bytes = new Uint8Array(REFRESH_TOKEN_BYTES);
  crypto.getRandomValues(bytes);
  return toHex(bytes);
}

export const sha256Digest: TokenDigest = {
  async compute(token: string): Promise<string> {
    const encoded = new TextEncoder().encode(`${DIGEST_DOMAIN}:${token}`);
    const digest = await crypto.subtle.digest('SHA-256', encoded);
    return toHex(new Uint8Array(digest));
  },
};

/**
 * Constant-time string comparison.
 *
 * Digest lookup is by an indexed equality, so the timing of *that* is a
 * database concern. This exists for the places a digest is compared in
 * application code, where an early-exit `===` would leak a prefix.
 */
export function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let difference = 0;
  for (let index = 0; index < a.length; index += 1) {
    difference |= a.charCodeAt(index) ^ b.charCodeAt(index);
  }
  return difference === 0;
}
