#!/usr/bin/env node
/**
 * Generates `THIRD-PARTY-NOTICES.md` from the licenses actually installed.
 *
 * Three packages are bundled into the shipped extension, and all three are
 * MIT. MIT is not a permission to use the code quietly: it requires that the
 * copyright notice and the permission notice travel with "all copies or
 * substantial portions of the Software". A minified React inside a published
 * extension is a substantial portion, so shipping without attribution is a
 * licence breach — a quiet one that nothing else in this repository would
 * have caught.
 *
 * The file is generated rather than written by hand for one reason: a
 * hand-written notice records the versions and holders that were true when
 * somebody last thought about it. `--check` re-generates and compares, so a
 * dependency bump that changes a version or a copyright holder fails the
 * build instead of leaving the notice quietly wrong.
 *
 * Only what is *bundled* is listed. Development dependencies — the compiler,
 * the test runner, the formatter — are not distributed to anyone, and listing
 * them would pad the file with attributions nobody is owed, which makes the
 * three that are owed harder to see.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(root, 'THIRD-PARTY-NOTICES.md');

/**
 * What reaches a user's browser.
 *
 * `scheduler` is not a direct dependency; it arrives through `react-dom` and
 * is bundled all the same, which is exactly the kind of package a
 * hand-maintained list forgets.
 */
const BUNDLED = ['react', 'react-dom', 'scheduler', 'zod'];

function packageInfo(name) {
  const dir = resolve(root, 'node_modules', name);
  if (!existsSync(dir)) {
    console.error(`✗ ${name} is not installed. Run \`npm ci\` first.`);
    process.exit(1);
  }
  const meta = JSON.parse(readFileSync(resolve(dir, 'package.json'), 'utf8'));
  const licenseFile = ['LICENSE', 'LICENSE.md', 'LICENSE.txt']
    .map((candidate) => resolve(dir, candidate))
    .find((candidate) => existsSync(candidate));
  if (!licenseFile) {
    console.error(`✗ ${name} ships no licence file, so its notice cannot be reproduced.`);
    process.exit(1);
  }
  return {
    name,
    version: meta.version,
    license: meta.license ?? 'UNSTATED',
    text: readFileSync(licenseFile, 'utf8').trim(),
    homepage: meta.homepage ?? `https://www.npmjs.com/package/${name}`,
  };
}

const packages = BUNDLED.map(packageInfo);

const body = `# Third-party notices

This extension bundles the following open-source packages into the artifact
that is distributed to users. Each is reproduced below with its licence, as
the licence requires.

This file is generated by \`scripts/generate-notices.mjs\` from the licences
actually installed, and \`npm run check:notices\` fails the build if it drifts
from them. It is not maintained by hand, because a hand-maintained notice
records whichever versions were true when somebody last remembered to look.

Only bundled packages are listed. Build and test tooling — the compiler, the
test runner, the formatter — is not distributed to anyone, so no attribution
is owed for it, and listing it would bury the attributions that are owed.

| Package | Version | Licence |
| ------- | ------- | ------- |
${packages.map((p) => `| [${p.name}](${p.homepage}) | ${p.version} | ${p.license} |`).join('\n')}

---

${packages
  .map(
    (p) => `## ${p.name} ${p.version}

${p.homepage}

\`\`\`text
${p.text}
\`\`\`
`,
  )
  .join('\n---\n\n')}`;

if (process.argv.includes('--check')) {
  if (!existsSync(OUTPUT)) {
    console.error('✗ THIRD-PARTY-NOTICES.md is missing. Run `npm run notices`.');
    process.exit(1);
  }
  if (readFileSync(OUTPUT, 'utf8') !== body) {
    console.error(
      '✗ THIRD-PARTY-NOTICES.md does not match the installed licences.\n' +
        '  A dependency changed version, holder or licence text. Run `npm run notices`.',
    );
    process.exit(1);
  }
  console.log(`✓ Third-party notices match the installed licences (${packages.length} packages).`);
  process.exit(0);
}

writeFileSync(OUTPUT, body);
console.log(`✓ Wrote THIRD-PARTY-NOTICES.md for ${packages.length} bundled packages:`);
for (const p of packages) console.log(`  ${p.name}@${p.version}  ${p.license}`);
