/**
 * TEST-SERVER-006 — Google ID token verification, one refusal branch at a time.
 *
 * This is the module that decides whether an authentication happened, so each
 * check gets a token that is genuinely wrong in exactly one way — signed with
 * a real key, by a real RS256 signature, over real claims. A test that passed
 * a hand-written string would prove the parser rejects garbage and nothing
 * about whether the verification is correct.
 *
 * The two forgeries worth naming are the header ones. `alg: none` and
 * `alg: HS256` both work against a verifier that reads the algorithm out of
 * the token it is checking, which is why the algorithm here comes from an
 * allowlist and the token's own claim is only ever compared to it.
 *
 * **Live Google acceptance is not tested here and is not claimed.** These
 * keys are generated by the test. Verifying against Google's real published
 * keys needs real Google credentials.
 */
import { beforeAll, describe, expect, it } from 'vitest';
import { GOOGLE_ISSUERS, CLOCK_SKEW_MS, verifyGoogleIdToken } from '@server/index';
import { GoogleFixture } from '../fixtures/google-oidc-fixture';

const NOW = 1_800_000_000_000;
const AUDIENCE = 'client-id.apps.googleusercontent.com';
const NONCE = 'n'.repeat(64);

describe('Google ID token verification', () => {
  let google: GoogleFixture;
  const base = { audience: AUDIENCE, nonce: NONCE, now: NOW };

  beforeAll(async () => {
    google = await GoogleFixture.create();
  });

  const verify = async (idToken: string, now = NOW) =>
    verifyGoogleIdToken({
      idToken,
      audience: AUDIENCE,
      expectedNonce: NONCE,
      now,
      jwks: google.jwks(),
    });

  describe('accepts a correct token', () => {
    it('returns only the claims this design uses', async () => {
      const token = await google.idToken(base, {
        sub: 'sub-123',
        email: 'person@example.com',
        email_verified: true,
      });
      const result = await verify(token);
      expect(result.ok).toBe(true);
      if (!result.ok) throw new Error('unreachable');
      expect(result.value).toEqual({
        subject: 'sub-123',
        email: 'person@example.com',
        emailVerified: true,
      });
    });

    it('accepts both of Google’s published issuer strings', async () => {
      for (const issuer of GOOGLE_ISSUERS) {
        const token = await google.idToken(base, { iss: issuer });
        expect((await verify(token)).ok, issuer).toBe(true);
      }
    });

    it('carries an unverified address through as unverified', async () => {
      const token = await google.idToken(base, {
        email: 'person@example.com',
        email_verified: false,
      });
      const result = await verify(token);
      expect(result.ok && result.value.emailVerified).toBe(false);
      expect(result.ok && result.value.email).toBe('person@example.com');
    });

    it('treats an absent email_verified claim as false, not as absent', async () => {
      const token = await google.idToken(base, { email: 'person@example.com' });
      const result = await verify(token);
      expect(result.ok && result.value.emailVerified).toBe(false);
    });
  });

  describe('header forgeries', () => {
    it('refuses alg: none', async () => {
      const token = await google.idToken(base, {}, { alg: 'none' });
      expect((await verify(token)).ok).toBe(false);
    });

    it('refuses alg: HS256 — the public key as an HMAC secret', async () => {
      const token = await google.idToken(base, {}, { alg: 'HS256' });
      expect((await verify(token)).ok).toBe(false);
    });

    it('refuses an unknown kid rather than trying every key', async () => {
      const token = await google.idToken(base, {}, { kid: 'not-a-real-key' });
      expect((await verify(token)).ok).toBe(false);
    });

    it('refuses a token with no kid', async () => {
      const token = await google.idToken(base);
      const [, payload, signature] = token.split('.') as [string, string, string];
      const headerNoKid = btoa(JSON.stringify({ alg: 'RS256', typ: 'JWT' }))
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=+$/, '');
      expect((await verify(`${headerNoKid}.${payload}.${signature}`)).ok).toBe(false);
    });

    it('refuses when the published key set does not contain the key', async () => {
      const token = await google.idToken(base);
      const result = await verifyGoogleIdToken({
        idToken: token,
        audience: AUDIENCE,
        expectedNonce: NONCE,
        now: NOW,
        jwks: GoogleFixture.emptyJwks(),
      });
      expect(result.ok).toBe(false);
    });
  });

  describe('signature', () => {
    it('refuses a token whose payload was altered after signing', async () => {
      expect((await verify(await google.tamperedToken(base))).ok).toBe(false);
    });

    it('refuses a token signed by a different key', async () => {
      const other = await GoogleFixture.create();
      // Same kid, different key: the signature must fail, not the lookup.
      const impostor = await GoogleFixture.create('test-key-1');
      const token = await impostor.idToken(base);
      expect((await verify(token)).ok).toBe(false);
      expect(other).toBeDefined();
    });

    it('refuses a malformed signature segment', async () => {
      const token = await google.idToken(base);
      const [head, payload] = token.split('.') as [string, string];
      expect((await verify(`${head}.${payload}.!!!not-base64url!!!`)).ok).toBe(false);
    });
  });

  describe('claims', () => {
    it('refuses a wrong issuer', async () => {
      for (const issuer of ['https://accounts.google.com.evil.test', 'https://evil.test', '']) {
        const token = await google.idToken(base, { iss: issuer });
        expect((await verify(token)).ok, issuer).toBe(false);
      }
    });

    it('refuses a wrong audience — another application’s token', async () => {
      const token = await google.idToken(base, { aud: 'someone-else.apps.googleusercontent.com' });
      expect((await verify(token)).ok).toBe(false);
    });

    it('refuses an expired token, at the skew boundary', async () => {
      const seconds = Math.floor(NOW / 1000);
      const token = await google.idToken(base, { exp: seconds });
      // Inside the skew window it still verifies.
      expect((await verify(token, NOW + CLOCK_SKEW_MS - 1)).ok).toBe(true);
      // At the boundary it does not.
      expect((await verify(token, NOW + CLOCK_SKEW_MS)).ok).toBe(false);
    });

    it('refuses a token issued implausibly far in the future', async () => {
      const seconds = Math.floor(NOW / 1000);
      const token = await google.idToken(base, { iat: seconds + 3600 });
      expect((await verify(token)).ok).toBe(false);
    });

    it('refuses a nonce that does not match this flow', async () => {
      const token = await google.idToken(base, { nonce: 'm'.repeat(64) });
      expect((await verify(token)).ok).toBe(false);
    });

    it('refuses a token with no nonce — replay of a token from another flow', async () => {
      const token = await google.idToken(base);
      const [head, , signature] = token.split('.') as [string, string, string];
      const seconds = Math.floor(NOW / 1000);
      const noNonce = btoa(
        JSON.stringify({
          iss: GOOGLE_ISSUERS[0],
          aud: AUDIENCE,
          sub: 's',
          exp: seconds + 3600,
          iat: seconds,
        }),
      )
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=+$/, '');
      expect((await verify(`${head}.${noNonce}.${signature}`)).ok).toBe(false);
    });

    it('refuses a token with no subject', async () => {
      const token = await google.idToken(base, { sub: '' });
      expect((await verify(token)).ok).toBe(false);
    });
  });

  describe('shape', () => {
    it('refuses anything that is not three segments', async () => {
      for (const candidate of ['', 'a', 'a.b', 'a.b.c.d']) {
        expect((await verify(candidate)).ok, candidate).toBe(false);
      }
    });

    it('refuses a header or payload that is not JSON', async () => {
      const notJson = btoa('hello').replace(/=+$/, '');
      expect((await verify(`${notJson}.${notJson}.${notJson}`)).ok).toBe(false);
    });
  });

  describe('failure reporting', () => {
    it('gives the same code for every refusal, so nothing is an oracle', async () => {
      const cases = [
        await google.idToken(base, { aud: 'other' }),
        await google.idToken(base, { iss: 'https://evil.test' }),
        await google.idToken(base, { nonce: 'wrong' }),
        await google.idToken(base, {}, { alg: 'none' }),
        await google.tamperedToken(base),
      ];
      for (const token of cases) {
        const result = await verify(token);
        expect(result.ok).toBe(false);
        if (result.ok) throw new Error('unreachable');
        expect(result.error.code).toBe('INVALID_ARGUMENT');
      }
    });
  });
});
